# .github/workflows/deploy-pr.yml

name: Deploy PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx build --platform linux/amd64 -t myapp:$GITHUB_SHA .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag myapp:$GITHUB_SHA $DOCKER_USERNAME/myapp:$GITHUB_SHA
        docker push $DOCKER_USERNAME/myapp:$GITHUB_SHA

    - name: Deploy to Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker pull $DOCKER_USERNAME/myapp:$GITHUB_SHA
        docker run --rm -d -p 3000:3000 $DOCKER_USERNAME/myapp:$GITHUB_SHA
